/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_GDaffiche (void);
GtkWidget* create_GDsupprime (void);
GtkWidget* create_GDajoute (void);
GtkWidget* create_GDmodife (void);
GtkWidget* create_GDstatistique (void);
