/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_GDaffiche (void)
{
  GtkWidget *GDaffiche;
  GtkWidget *fixed1;
  GtkWidget *treeviewGD;
  GtkWidget *GDsearchEntry;
  GtkWidget *GDdeconnexcion;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image2;
  GtkWidget *label2;
  GtkWidget *GDstatistiqueWidget;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image7;
  GtkWidget *label7;
  GtkWidget *GDactualiser;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image6;
  GtkWidget *label6;
  GtkWidget *GDsupprimerWidget;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image5;
  GtkWidget *label5;
  GtkWidget *GDmodifierWidget;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image4;
  GtkWidget *label4;
  GtkWidget *GDajoutWidget;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image3;
  GtkWidget *label3;
  GtkWidget *GDsearchButton;
  GtkWidget *image1;
  GtkWidget *label1;

  GDaffiche = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (GDaffiche, 990, 801);
  gtk_window_set_title (GTK_WINDOW (GDaffiche), _("Gestion Des demandes"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (GDaffiche), fixed1);
  gtk_widget_set_size_request (fixed1, 939, 754);

  treeviewGD = gtk_tree_view_new ();
  gtk_widget_show (treeviewGD);
  gtk_fixed_put (GTK_FIXED (fixed1), treeviewGD, 56, 240);
  gtk_widget_set_size_request (treeviewGD, 568, 448);

  GDsearchEntry = gtk_entry_new ();
  gtk_widget_show (GDsearchEntry);
  gtk_fixed_put (GTK_FIXED (fixed1), GDsearchEntry, 168, 152);
  gtk_widget_set_size_request (GDsearchEntry, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (GDsearchEntry), 8226);

  GDdeconnexcion = gtk_button_new ();
  gtk_widget_show (GDdeconnexcion);
  gtk_fixed_put (GTK_FIXED (fixed1), GDdeconnexcion, 56, 48);
  gtk_widget_set_size_request (GDdeconnexcion, 122, 45);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (GDdeconnexcion), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image2 = gtk_image_new_from_stock ("gtk-media-stop", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox1), image2, FALSE, FALSE, 0);

  label2 = gtk_label_new_with_mnemonic (_("Deconnexion"));
  gtk_widget_show (label2);
  gtk_box_pack_start (GTK_BOX (hbox1), label2, FALSE, FALSE, 0);

  GDstatistiqueWidget = gtk_button_new ();
  gtk_widget_show (GDstatistiqueWidget);
  gtk_fixed_put (GTK_FIXED (fixed1), GDstatistiqueWidget, 720, 696);
  gtk_widget_set_size_request (GDstatistiqueWidget, 219, 58);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (GDstatistiqueWidget), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image7 = gtk_image_new_from_stock ("gtk-fullscreen", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox6), image7, FALSE, FALSE, 0);

  label7 = gtk_label_new_with_mnemonic (_("Statistique"));
  gtk_widget_show (label7);
  gtk_box_pack_start (GTK_BOX (hbox6), label7, FALSE, FALSE, 0);

  GDactualiser = gtk_button_new ();
  gtk_widget_show (GDactualiser);
  gtk_fixed_put (GTK_FIXED (fixed1), GDactualiser, 720, 560);
  gtk_widget_set_size_request (GDactualiser, 219, 58);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (GDactualiser), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image6 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox5), image6, FALSE, FALSE, 0);

  label6 = gtk_label_new_with_mnemonic (_("Actualiser"));
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (hbox5), label6, FALSE, FALSE, 0);

  GDsupprimerWidget = gtk_button_new ();
  gtk_widget_show (GDsupprimerWidget);
  gtk_fixed_put (GTK_FIXED (fixed1), GDsupprimerWidget, 720, 416);
  gtk_widget_set_size_request (GDsupprimerWidget, 219, 58);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (GDsupprimerWidget), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image5 = gtk_image_new_from_stock ("gtk-stop", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox4), image5, FALSE, FALSE, 0);

  label5 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (hbox4), label5, FALSE, FALSE, 0);

  GDmodifierWidget = gtk_button_new ();
  gtk_widget_show (GDmodifierWidget);
  gtk_fixed_put (GTK_FIXED (fixed1), GDmodifierWidget, 720, 296);
  gtk_widget_set_size_request (GDmodifierWidget, 219, 58);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (GDmodifierWidget), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image4 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox3), image4, FALSE, FALSE, 0);

  label4 = gtk_label_new_with_mnemonic (_("Modification"));
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (hbox3), label4, FALSE, FALSE, 0);

  GDajoutWidget = gtk_button_new ();
  gtk_widget_show (GDajoutWidget);
  gtk_fixed_put (GTK_FIXED (fixed1), GDajoutWidget, 720, 176);
  gtk_widget_set_size_request (GDajoutWidget, 219, 58);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (GDajoutWidget), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image3 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox2), image3, FALSE, FALSE, 0);

  label3 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (hbox2), label3, FALSE, FALSE, 0);

  GDsearchButton = gtk_button_new ();
  gtk_widget_show (GDsearchButton);
  gtk_fixed_put (GTK_FIXED (fixed1), GDsearchButton, 344, 152);
  gtk_widget_set_size_request (GDsearchButton, 58, 29);

  image1 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_container_add (GTK_CONTAINER (GDsearchButton), image1);

  label1 = gtk_label_new (_("Gestion Des demandes"));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed1), label1, 408, 64);
  gtk_widget_set_size_request (label1, 193, 17);

  g_signal_connect ((gpointer) treeviewGD, "row_activated",
                    G_CALLBACK (on_treeviewGD_row_activated),
                    NULL);
  g_signal_connect ((gpointer) GDdeconnexcion, "clicked",
                    G_CALLBACK (on_GDdeconnexcion_clicked),
                    NULL);
  g_signal_connect ((gpointer) GDstatistiqueWidget, "clicked",
                    G_CALLBACK (on_GDstatistiqueWidget_clicked),
                    NULL);
  g_signal_connect ((gpointer) GDactualiser, "clicked",
                    G_CALLBACK (on_GDactualiser_clicked),
                    NULL);
  g_signal_connect ((gpointer) GDsupprimerWidget, "clicked",
                    G_CALLBACK (on_GDsupprimerWidget_clicked),
                    NULL);
  g_signal_connect ((gpointer) GDmodifierWidget, "clicked",
                    G_CALLBACK (on_GDmodifierWidget_clicked),
                    NULL);
  g_signal_connect ((gpointer) GDajoutWidget, "clicked",
                    G_CALLBACK (on_GDajoutWidget_clicked),
                    NULL);
  g_signal_connect ((gpointer) GDsearchButton, "clicked",
                    G_CALLBACK (on_GDsearchButton_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (GDaffiche, GDaffiche, "GDaffiche");
  GLADE_HOOKUP_OBJECT (GDaffiche, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (GDaffiche, treeviewGD, "treeviewGD");
  GLADE_HOOKUP_OBJECT (GDaffiche, GDsearchEntry, "GDsearchEntry");
  GLADE_HOOKUP_OBJECT (GDaffiche, GDdeconnexcion, "GDdeconnexcion");
  GLADE_HOOKUP_OBJECT (GDaffiche, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (GDaffiche, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (GDaffiche, image2, "image2");
  GLADE_HOOKUP_OBJECT (GDaffiche, label2, "label2");
  GLADE_HOOKUP_OBJECT (GDaffiche, GDstatistiqueWidget, "GDstatistiqueWidget");
  GLADE_HOOKUP_OBJECT (GDaffiche, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (GDaffiche, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (GDaffiche, image7, "image7");
  GLADE_HOOKUP_OBJECT (GDaffiche, label7, "label7");
  GLADE_HOOKUP_OBJECT (GDaffiche, GDactualiser, "GDactualiser");
  GLADE_HOOKUP_OBJECT (GDaffiche, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (GDaffiche, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (GDaffiche, image6, "image6");
  GLADE_HOOKUP_OBJECT (GDaffiche, label6, "label6");
  GLADE_HOOKUP_OBJECT (GDaffiche, GDsupprimerWidget, "GDsupprimerWidget");
  GLADE_HOOKUP_OBJECT (GDaffiche, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (GDaffiche, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (GDaffiche, image5, "image5");
  GLADE_HOOKUP_OBJECT (GDaffiche, label5, "label5");
  GLADE_HOOKUP_OBJECT (GDaffiche, GDmodifierWidget, "GDmodifierWidget");
  GLADE_HOOKUP_OBJECT (GDaffiche, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (GDaffiche, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (GDaffiche, image4, "image4");
  GLADE_HOOKUP_OBJECT (GDaffiche, label4, "label4");
  GLADE_HOOKUP_OBJECT (GDaffiche, GDajoutWidget, "GDajoutWidget");
  GLADE_HOOKUP_OBJECT (GDaffiche, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (GDaffiche, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (GDaffiche, image3, "image3");
  GLADE_HOOKUP_OBJECT (GDaffiche, label3, "label3");
  GLADE_HOOKUP_OBJECT (GDaffiche, GDsearchButton, "GDsearchButton");
  GLADE_HOOKUP_OBJECT (GDaffiche, image1, "image1");
  GLADE_HOOKUP_OBJECT (GDaffiche, label1, "label1");

  return GDaffiche;
}

GtkWidget*
create_GDsupprime (void)
{
  GtkWidget *GDsupprime;
  GtkWidget *fixed2;
  GtkWidget *GDidEntrySupprimer;
  GtkWidget *label8;
  GtkWidget *label9;
  GtkWidget *GDcontroleSaisiSupprimer;
  GtkWidget *GDsupprimerButton;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image8;
  GtkWidget *label10;
  GtkWidget *GDannulerSupprimerButton;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image9;
  GtkWidget *label11;

  GDsupprime = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (GDsupprime, 486, 275);
  gtk_window_set_title (GTK_WINDOW (GDsupprime), _("Supprimer Des demandes"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (GDsupprime), fixed2);

  GDidEntrySupprimer = gtk_entry_new ();
  gtk_widget_show (GDidEntrySupprimer);
  gtk_fixed_put (GTK_FIXED (fixed2), GDidEntrySupprimer, 168, 104);
  gtk_widget_set_size_request (GDidEntrySupprimer, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (GDidEntrySupprimer), 8226);

  label8 = gtk_label_new (_("ID"));
  gtk_widget_show (label8);
  gtk_fixed_put (GTK_FIXED (fixed2), label8, 88, 112);
  gtk_widget_set_size_request (label8, 49, 17);

  label9 = gtk_label_new (_("Supprimer Des demandes"));
  gtk_widget_show (label9);
  gtk_fixed_put (GTK_FIXED (fixed2), label9, 160, 48);
  gtk_widget_set_size_request (label9, 179, 17);

  GDcontroleSaisiSupprimer = gtk_label_new ("");
  gtk_widget_show (GDcontroleSaisiSupprimer);
  gtk_fixed_put (GTK_FIXED (fixed2), GDcontroleSaisiSupprimer, 112, 160);
  gtk_widget_set_size_request (GDcontroleSaisiSupprimer, 300, 23);

  GDsupprimerButton = gtk_button_new ();
  gtk_widget_show (GDsupprimerButton);
  gtk_fixed_put (GTK_FIXED (fixed2), GDsupprimerButton, 264, 208);
  gtk_widget_set_size_request (GDsupprimerButton, 150, 40);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (GDsupprimerButton), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image8 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox7), image8, FALSE, FALSE, 0);

  label10 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label10);
  gtk_box_pack_start (GTK_BOX (hbox7), label10, FALSE, FALSE, 0);

  GDannulerSupprimerButton = gtk_button_new ();
  gtk_widget_show (GDannulerSupprimerButton);
  gtk_fixed_put (GTK_FIXED (fixed2), GDannulerSupprimerButton, 104, 208);
  gtk_widget_set_size_request (GDannulerSupprimerButton, 150, 40);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (GDannulerSupprimerButton), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image9 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox8), image9, FALSE, FALSE, 0);

  label11 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label11);
  gtk_box_pack_start (GTK_BOX (hbox8), label11, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) GDsupprimerButton, "clicked",
                    G_CALLBACK (on_GDsupprimerButton_clicked),
                    NULL);
  g_signal_connect ((gpointer) GDannulerSupprimerButton, "clicked",
                    G_CALLBACK (on_GDannulerSupprimerButton_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (GDsupprime, GDsupprime, "GDsupprime");
  GLADE_HOOKUP_OBJECT (GDsupprime, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (GDsupprime, GDidEntrySupprimer, "GDidEntrySupprimer");
  GLADE_HOOKUP_OBJECT (GDsupprime, label8, "label8");
  GLADE_HOOKUP_OBJECT (GDsupprime, label9, "label9");
  GLADE_HOOKUP_OBJECT (GDsupprime, GDcontroleSaisiSupprimer, "GDcontroleSaisiSupprimer");
  GLADE_HOOKUP_OBJECT (GDsupprime, GDsupprimerButton, "GDsupprimerButton");
  GLADE_HOOKUP_OBJECT (GDsupprime, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (GDsupprime, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (GDsupprime, image8, "image8");
  GLADE_HOOKUP_OBJECT (GDsupprime, label10, "label10");
  GLADE_HOOKUP_OBJECT (GDsupprime, GDannulerSupprimerButton, "GDannulerSupprimerButton");
  GLADE_HOOKUP_OBJECT (GDsupprime, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (GDsupprime, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (GDsupprime, image9, "image9");
  GLADE_HOOKUP_OBJECT (GDsupprime, label11, "label11");

  return GDsupprime;
}

GtkWidget*
create_GDajoute (void)
{
  GtkWidget *GDajoute;
  GtkWidget *fixed3;
  GtkWidget *GDidEntryAjout;
  GtkWidget *label13;
  GtkWidget *label15;
  GtkWidget *label16;
  GtkObject *GDjjSpinAjout_adj;
  GtkWidget *GDjjSpinAjout;
  GtkObject *GDmmSpinAjout_adj;
  GtkWidget *GDmmSpinAjout;
  GtkWidget *label17;
  GtkWidget *label18;
  GtkObject *GDyySpinAjout_adj;
  GtkWidget *GDyySpinAjout;
  GtkWidget *label19;
  GtkWidget *label28;
  GtkObject *GDquantiteSpinAjout_adj;
  GtkWidget *GDquantiteSpinAjout;
  GtkWidget *label22;
  GtkWidget *label23;
  GtkWidget *label21;
  GtkWidget *label24;
  GtkWidget *GDannulerAjoutButton;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image10;
  GtkWidget *label25;
  GtkWidget *GDajoutButton;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image11;
  GtkWidget *label26;
  GtkWidget *GDTraiteStatusAjout;
  GtkWidget *GDCoursStatusAjout;
  GtkWidget *GDnonUrgenceAjout;
  GSList *GDnonUrgenceAjout_group = NULL;
  GtkWidget *GDouiUrgenceAjout;
  GtkWidget *GDcontroleSaisiAjout;
  GtkWidget *GDetabComboAjout1;
  GtkWidget *GDtypeSangComboAjout1;

  GDajoute = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (GDajoute, 891, 858);
  gtk_window_set_title (GTK_WINDOW (GDajoute), _("Ajout Demande"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (GDajoute), fixed3);

  GDidEntryAjout = gtk_entry_new ();
  gtk_widget_show (GDidEntryAjout);
  gtk_fixed_put (GTK_FIXED (fixed3), GDidEntryAjout, 344, 144);
  gtk_widget_set_size_request (GDidEntryAjout, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (GDidEntryAjout), 8226);

  label13 = gtk_label_new (_("ID"));
  gtk_widget_show (label13);
  gtk_fixed_put (GTK_FIXED (fixed3), label13, 272, 152);
  gtk_widget_set_size_request (label13, 49, 17);

  label15 = gtk_label_new (_("etablissement"));
  gtk_widget_show (label15);
  gtk_fixed_put (GTK_FIXED (fixed3), label15, 232, 248);
  gtk_widget_set_size_request (label15, 111, 17);

  label16 = gtk_label_new (_("Jour"));
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed3), label16, 296, 352);
  gtk_widget_set_size_request (label16, 49, 17);

  GDjjSpinAjout_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  GDjjSpinAjout = gtk_spin_button_new (GTK_ADJUSTMENT (GDjjSpinAjout_adj), 1, 0);
  gtk_widget_show (GDjjSpinAjout);
  gtk_fixed_put (GTK_FIXED (fixed3), GDjjSpinAjout, 360, 344);
  gtk_widget_set_size_request (GDjjSpinAjout, 60, 27);

  GDmmSpinAjout_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  GDmmSpinAjout = gtk_spin_button_new (GTK_ADJUSTMENT (GDmmSpinAjout_adj), 1, 0);
  gtk_widget_show (GDmmSpinAjout);
  gtk_fixed_put (GTK_FIXED (fixed3), GDmmSpinAjout, 536, 344);
  gtk_widget_set_size_request (GDmmSpinAjout, 60, 27);

  label17 = gtk_label_new (_("Mois"));
  gtk_widget_show (label17);
  gtk_fixed_put (GTK_FIXED (fixed3), label17, 480, 352);
  gtk_widget_set_size_request (label17, 49, 17);

  label18 = gtk_label_new (_("Ann\303\251e"));
  gtk_widget_show (label18);
  gtk_fixed_put (GTK_FIXED (fixed3), label18, 656, 352);
  gtk_widget_set_size_request (label18, 49, 17);

  GDyySpinAjout_adj = gtk_adjustment_new (2023, 1950, 2024, 1, 10, 10);
  GDyySpinAjout = gtk_spin_button_new (GTK_ADJUSTMENT (GDyySpinAjout_adj), 1, 0);
  gtk_widget_show (GDyySpinAjout);
  gtk_fixed_put (GTK_FIXED (fixed3), GDyySpinAjout, 720, 344);
  gtk_widget_set_size_request (GDyySpinAjout, 60, 27);

  label19 = gtk_label_new (_("Date"));
  gtk_widget_show (label19);
  gtk_fixed_put (GTK_FIXED (fixed3), label19, 208, 352);
  gtk_widget_set_size_request (label19, 49, 17);

  label28 = gtk_label_new (_("quantite"));
  gtk_widget_show (label28);
  gtk_fixed_put (GTK_FIXED (fixed3), label28, 256, 208);
  gtk_widget_set_size_request (label28, 65, 17);

  GDquantiteSpinAjout_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  GDquantiteSpinAjout = gtk_spin_button_new (GTK_ADJUSTMENT (GDquantiteSpinAjout_adj), 1, 0);
  gtk_widget_show (GDquantiteSpinAjout);
  gtk_fixed_put (GTK_FIXED (fixed3), GDquantiteSpinAjout, 352, 200);
  gtk_widget_set_size_request (GDquantiteSpinAjout, 60, 27);

  label22 = gtk_label_new (_("urgence"));
  gtk_widget_show (label22);
  gtk_fixed_put (GTK_FIXED (fixed3), label22, 208, 528);
  gtk_widget_set_size_request (label22, 56, 17);

  label23 = gtk_label_new (_("status"));
  gtk_widget_show (label23);
  gtk_fixed_put (GTK_FIXED (fixed3), label23, 200, 592);
  gtk_widget_set_size_request (label23, 72, 17);

  label21 = gtk_label_new (_("Type de Sang"));
  gtk_widget_show (label21);
  gtk_fixed_put (GTK_FIXED (fixed3), label21, 176, 440);
  gtk_widget_set_size_request (label21, 112, 17);

  label24 = gtk_label_new (_("Ajouter Demande"));
  gtk_widget_show (label24);
  gtk_fixed_put (GTK_FIXED (fixed3), label24, 304, 72);
  gtk_widget_set_size_request (label24, 300, 17);

  GDannulerAjoutButton = gtk_button_new ();
  gtk_widget_show (GDannulerAjoutButton);
  gtk_fixed_put (GTK_FIXED (fixed3), GDannulerAjoutButton, 96, 752);
  gtk_widget_set_size_request (GDannulerAjoutButton, 219, 58);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (GDannulerAjoutButton), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image10 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox9), image10, FALSE, FALSE, 0);

  label25 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label25);
  gtk_box_pack_start (GTK_BOX (hbox9), label25, FALSE, FALSE, 0);

  GDajoutButton = gtk_button_new ();
  gtk_widget_show (GDajoutButton);
  gtk_fixed_put (GTK_FIXED (fixed3), GDajoutButton, 592, 752);
  gtk_widget_set_size_request (GDajoutButton, 219, 58);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (GDajoutButton), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image11 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox10), image11, FALSE, FALSE, 0);

  label26 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label26);
  gtk_box_pack_start (GTK_BOX (hbox10), label26, FALSE, FALSE, 0);

  GDTraiteStatusAjout = gtk_check_button_new_with_mnemonic (_("trait\303\251"));
  gtk_widget_show (GDTraiteStatusAjout);
  gtk_fixed_put (GTK_FIXED (fixed3), GDTraiteStatusAjout, 416, 592);
  gtk_widget_set_size_request (GDTraiteStatusAjout, 118, 24);

  GDCoursStatusAjout = gtk_check_button_new_with_mnemonic (_("en cours"));
  gtk_widget_show (GDCoursStatusAjout);
  gtk_fixed_put (GTK_FIXED (fixed3), GDCoursStatusAjout, 280, 592);
  gtk_widget_set_size_request (GDCoursStatusAjout, 118, 24);

  GDnonUrgenceAjout = gtk_radio_button_new_with_mnemonic (NULL, _("non"));
  gtk_widget_show (GDnonUrgenceAjout);
  gtk_fixed_put (GTK_FIXED (fixed3), GDnonUrgenceAjout, 400, 528);
  gtk_widget_set_size_request (GDnonUrgenceAjout, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (GDnonUrgenceAjout), GDnonUrgenceAjout_group);
  GDnonUrgenceAjout_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (GDnonUrgenceAjout));

  GDouiUrgenceAjout = gtk_radio_button_new_with_mnemonic (NULL, _("oui"));
  gtk_widget_show (GDouiUrgenceAjout);
  gtk_fixed_put (GTK_FIXED (fixed3), GDouiUrgenceAjout, 280, 528);
  gtk_widget_set_size_request (GDouiUrgenceAjout, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (GDouiUrgenceAjout), GDnonUrgenceAjout_group);
  GDnonUrgenceAjout_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (GDouiUrgenceAjout));

  GDcontroleSaisiAjout = gtk_label_new ("");
  gtk_widget_show (GDcontroleSaisiAjout);
  gtk_fixed_put (GTK_FIXED (fixed3), GDcontroleSaisiAjout, 320, 664);
  gtk_widget_set_size_request (GDcontroleSaisiAjout, 300, 25);

  GDetabComboAjout1 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (GDetabComboAjout1);
  gtk_fixed_put (GTK_FIXED (fixed3), GDetabComboAjout1, 360, 240);
  gtk_widget_set_size_request (GDetabComboAjout1, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (GDetabComboAjout1), _("etabSang"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (GDetabComboAjout1), _("etab2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (GDetabComboAjout1), _("etab3"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (GDetabComboAjout1), _("etab4"));

  GDtypeSangComboAjout1 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (GDtypeSangComboAjout1);
  gtk_fixed_put (GTK_FIXED (fixed3), GDtypeSangComboAjout1, 296, 440);
  gtk_widget_set_size_request (GDtypeSangComboAjout1, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (GDtypeSangComboAjout1), _("A+"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (GDtypeSangComboAjout1), _("A-"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (GDtypeSangComboAjout1), _("B+"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (GDtypeSangComboAjout1), _("B-"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (GDtypeSangComboAjout1), _("O+"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (GDtypeSangComboAjout1), _("O-"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (GDtypeSangComboAjout1), _("AB+"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (GDtypeSangComboAjout1), _("AB-"));

  g_signal_connect ((gpointer) GDannulerAjoutButton, "clicked",
                    G_CALLBACK (on_GDannulerAjoutButton_clicked),
                    NULL);
  g_signal_connect ((gpointer) GDajoutButton, "clicked",
                    G_CALLBACK (on_GDajoutButton_clicked),
                    NULL);
  g_signal_connect ((gpointer) GDTraiteStatusAjout, "toggled",
                    G_CALLBACK (on_GDTraiteStatusAjout_toggled),
                    NULL);
  g_signal_connect ((gpointer) GDCoursStatusAjout, "toggled",
                    G_CALLBACK (on_GDCoursStatusAjout_toggled),
                    NULL);
  g_signal_connect ((gpointer) GDnonUrgenceAjout, "toggled",
                    G_CALLBACK (on_GDnonUrgenceAjout_toggled),
                    NULL);
  g_signal_connect ((gpointer) GDouiUrgenceAjout, "toggled",
                    G_CALLBACK (on_GDouiUrgenceAjout_toggled),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (GDajoute, GDajoute, "GDajoute");
  GLADE_HOOKUP_OBJECT (GDajoute, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (GDajoute, GDidEntryAjout, "GDidEntryAjout");
  GLADE_HOOKUP_OBJECT (GDajoute, label13, "label13");
  GLADE_HOOKUP_OBJECT (GDajoute, label15, "label15");
  GLADE_HOOKUP_OBJECT (GDajoute, label16, "label16");
  GLADE_HOOKUP_OBJECT (GDajoute, GDjjSpinAjout, "GDjjSpinAjout");
  GLADE_HOOKUP_OBJECT (GDajoute, GDmmSpinAjout, "GDmmSpinAjout");
  GLADE_HOOKUP_OBJECT (GDajoute, label17, "label17");
  GLADE_HOOKUP_OBJECT (GDajoute, label18, "label18");
  GLADE_HOOKUP_OBJECT (GDajoute, GDyySpinAjout, "GDyySpinAjout");
  GLADE_HOOKUP_OBJECT (GDajoute, label19, "label19");
  GLADE_HOOKUP_OBJECT (GDajoute, label28, "label28");
  GLADE_HOOKUP_OBJECT (GDajoute, GDquantiteSpinAjout, "GDquantiteSpinAjout");
  GLADE_HOOKUP_OBJECT (GDajoute, label22, "label22");
  GLADE_HOOKUP_OBJECT (GDajoute, label23, "label23");
  GLADE_HOOKUP_OBJECT (GDajoute, label21, "label21");
  GLADE_HOOKUP_OBJECT (GDajoute, label24, "label24");
  GLADE_HOOKUP_OBJECT (GDajoute, GDannulerAjoutButton, "GDannulerAjoutButton");
  GLADE_HOOKUP_OBJECT (GDajoute, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (GDajoute, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (GDajoute, image10, "image10");
  GLADE_HOOKUP_OBJECT (GDajoute, label25, "label25");
  GLADE_HOOKUP_OBJECT (GDajoute, GDajoutButton, "GDajoutButton");
  GLADE_HOOKUP_OBJECT (GDajoute, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (GDajoute, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (GDajoute, image11, "image11");
  GLADE_HOOKUP_OBJECT (GDajoute, label26, "label26");
  GLADE_HOOKUP_OBJECT (GDajoute, GDTraiteStatusAjout, "GDTraiteStatusAjout");
  GLADE_HOOKUP_OBJECT (GDajoute, GDCoursStatusAjout, "GDCoursStatusAjout");
  GLADE_HOOKUP_OBJECT (GDajoute, GDnonUrgenceAjout, "GDnonUrgenceAjout");
  GLADE_HOOKUP_OBJECT (GDajoute, GDouiUrgenceAjout, "GDouiUrgenceAjout");
  GLADE_HOOKUP_OBJECT (GDajoute, GDcontroleSaisiAjout, "GDcontroleSaisiAjout");
  GLADE_HOOKUP_OBJECT (GDajoute, GDetabComboAjout1, "GDetabComboAjout1");
  GLADE_HOOKUP_OBJECT (GDajoute, GDtypeSangComboAjout1, "GDtypeSangComboAjout1");

  return GDajoute;
}

GtkWidget*
create_GDmodife (void)
{
  GtkWidget *GDmodife;
  GtkWidget *fixed4;
  GtkWidget *GDidEntryModifier;
  GtkWidget *label29;
  GtkWidget *label30;
  GtkWidget *label31;
  GtkObject *GDjjSpinModifier_adj;
  GtkWidget *GDjjSpinModifier;
  GtkObject *GDmmSpinModifier_adj;
  GtkWidget *GDmmSpinModifier;
  GtkWidget *label32;
  GtkWidget *label33;
  GtkObject *GDyySpinModifier_adj;
  GtkWidget *GDyySpinModifier;
  GtkWidget *label34;
  GtkWidget *label40;
  GtkObject *GDquantiteSpinModifier_adj;
  GtkWidget *GDquantiteSpinModifier;
  GtkWidget *label42;
  GtkWidget *label41;
  GtkWidget *label39;
  GtkWidget *label35;
  GtkWidget *GDannulerModifierButton;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image12;
  GtkWidget *label36;
  GtkWidget *GDouiUrgenceModifier;
  GSList *GDouiUrgenceModifier_group = NULL;
  GtkWidget *GDnonUrgenceModifier;
  GtkWidget *GDTraiteStatusModifier;
  GtkWidget *GDCoursStatusModifier;
  GtkWidget *GDModifierButton;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image13;
  GtkWidget *label37;
  GtkWidget *GDcontroleSaisiModifier;
  GtkWidget *GDetabComboModifier1;
  GtkWidget *GDtypeSangComboModifier1;

  GDmodife = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (GDmodife, 891, 858);
  gtk_window_set_title (GTK_WINDOW (GDmodife), _("Modifier Demande"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (GDmodife), fixed4);

  GDidEntryModifier = gtk_entry_new ();
  gtk_widget_show (GDidEntryModifier);
  gtk_fixed_put (GTK_FIXED (fixed4), GDidEntryModifier, 344, 144);
  gtk_widget_set_size_request (GDidEntryModifier, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (GDidEntryModifier), 8226);

  label29 = gtk_label_new (_("ID"));
  gtk_widget_show (label29);
  gtk_fixed_put (GTK_FIXED (fixed4), label29, 272, 152);
  gtk_widget_set_size_request (label29, 49, 17);

  label30 = gtk_label_new (_("etablissement"));
  gtk_widget_show (label30);
  gtk_fixed_put (GTK_FIXED (fixed4), label30, 232, 248);
  gtk_widget_set_size_request (label30, 111, 17);

  label31 = gtk_label_new (_("Jour"));
  gtk_widget_show (label31);
  gtk_fixed_put (GTK_FIXED (fixed4), label31, 296, 352);
  gtk_widget_set_size_request (label31, 49, 17);

  GDjjSpinModifier_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  GDjjSpinModifier = gtk_spin_button_new (GTK_ADJUSTMENT (GDjjSpinModifier_adj), 1, 0);
  gtk_widget_show (GDjjSpinModifier);
  gtk_fixed_put (GTK_FIXED (fixed4), GDjjSpinModifier, 368, 344);
  gtk_widget_set_size_request (GDjjSpinModifier, 60, 27);

  GDmmSpinModifier_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  GDmmSpinModifier = gtk_spin_button_new (GTK_ADJUSTMENT (GDmmSpinModifier_adj), 1, 0);
  gtk_widget_show (GDmmSpinModifier);
  gtk_fixed_put (GTK_FIXED (fixed4), GDmmSpinModifier, 536, 344);
  gtk_widget_set_size_request (GDmmSpinModifier, 60, 27);

  label32 = gtk_label_new (_("Mois"));
  gtk_widget_show (label32);
  gtk_fixed_put (GTK_FIXED (fixed4), label32, 480, 352);
  gtk_widget_set_size_request (label32, 49, 17);

  label33 = gtk_label_new (_("Ann\303\251e"));
  gtk_widget_show (label33);
  gtk_fixed_put (GTK_FIXED (fixed4), label33, 656, 352);
  gtk_widget_set_size_request (label33, 49, 17);

  GDyySpinModifier_adj = gtk_adjustment_new (2023, 1950, 2024, 1, 10, 10);
  GDyySpinModifier = gtk_spin_button_new (GTK_ADJUSTMENT (GDyySpinModifier_adj), 1, 0);
  gtk_widget_show (GDyySpinModifier);
  gtk_fixed_put (GTK_FIXED (fixed4), GDyySpinModifier, 720, 344);
  gtk_widget_set_size_request (GDyySpinModifier, 60, 27);

  label34 = gtk_label_new (_("Date"));
  gtk_widget_show (label34);
  gtk_fixed_put (GTK_FIXED (fixed4), label34, 208, 352);
  gtk_widget_set_size_request (label34, 49, 17);

  label40 = gtk_label_new (_("quantite"));
  gtk_widget_show (label40);
  gtk_fixed_put (GTK_FIXED (fixed4), label40, 256, 208);
  gtk_widget_set_size_request (label40, 65, 17);

  GDquantiteSpinModifier_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  GDquantiteSpinModifier = gtk_spin_button_new (GTK_ADJUSTMENT (GDquantiteSpinModifier_adj), 1, 0);
  gtk_widget_show (GDquantiteSpinModifier);
  gtk_fixed_put (GTK_FIXED (fixed4), GDquantiteSpinModifier, 376, 200);
  gtk_widget_set_size_request (GDquantiteSpinModifier, 60, 27);

  label42 = gtk_label_new (_("status"));
  gtk_widget_show (label42);
  gtk_fixed_put (GTK_FIXED (fixed4), label42, 200, 592);
  gtk_widget_set_size_request (label42, 72, 17);

  label41 = gtk_label_new (_("urgence"));
  gtk_widget_show (label41);
  gtk_fixed_put (GTK_FIXED (fixed4), label41, 208, 528);
  gtk_widget_set_size_request (label41, 56, 17);

  label39 = gtk_label_new (_("Type de Sang"));
  gtk_widget_show (label39);
  gtk_fixed_put (GTK_FIXED (fixed4), label39, 176, 440);
  gtk_widget_set_size_request (label39, 100, 17);

  label35 = gtk_label_new (_("Modifier Demande"));
  gtk_widget_show (label35);
  gtk_fixed_put (GTK_FIXED (fixed4), label35, 344, 72);
  gtk_widget_set_size_request (label35, 300, 17);

  GDannulerModifierButton = gtk_button_new ();
  gtk_widget_show (GDannulerModifierButton);
  gtk_fixed_put (GTK_FIXED (fixed4), GDannulerModifierButton, 224, 752);
  gtk_widget_set_size_request (GDannulerModifierButton, 219, 58);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (GDannulerModifierButton), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image12 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox11), image12, FALSE, FALSE, 0);

  label36 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label36);
  gtk_box_pack_start (GTK_BOX (hbox11), label36, FALSE, FALSE, 0);

  GDouiUrgenceModifier = gtk_radio_button_new_with_mnemonic (NULL, _("oui"));
  gtk_widget_show (GDouiUrgenceModifier);
  gtk_fixed_put (GTK_FIXED (fixed4), GDouiUrgenceModifier, 280, 528);
  gtk_widget_set_size_request (GDouiUrgenceModifier, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (GDouiUrgenceModifier), GDouiUrgenceModifier_group);
  GDouiUrgenceModifier_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (GDouiUrgenceModifier));

  GDnonUrgenceModifier = gtk_radio_button_new_with_mnemonic (NULL, _("non"));
  gtk_widget_show (GDnonUrgenceModifier);
  gtk_fixed_put (GTK_FIXED (fixed4), GDnonUrgenceModifier, 416, 528);
  gtk_widget_set_size_request (GDnonUrgenceModifier, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (GDnonUrgenceModifier), GDouiUrgenceModifier_group);
  GDouiUrgenceModifier_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (GDnonUrgenceModifier));

  GDTraiteStatusModifier = gtk_check_button_new_with_mnemonic (_("trait\303\251"));
  gtk_widget_show (GDTraiteStatusModifier);
  gtk_fixed_put (GTK_FIXED (fixed4), GDTraiteStatusModifier, 416, 592);
  gtk_widget_set_size_request (GDTraiteStatusModifier, 118, 24);

  GDCoursStatusModifier = gtk_check_button_new_with_mnemonic (_("en cours"));
  gtk_widget_show (GDCoursStatusModifier);
  gtk_fixed_put (GTK_FIXED (fixed4), GDCoursStatusModifier, 280, 592);
  gtk_widget_set_size_request (GDCoursStatusModifier, 118, 24);

  GDModifierButton = gtk_button_new ();
  gtk_widget_show (GDModifierButton);
  gtk_fixed_put (GTK_FIXED (fixed4), GDModifierButton, 592, 752);
  gtk_widget_set_size_request (GDModifierButton, 219, 58);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (GDModifierButton), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image13 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox12), image13, FALSE, FALSE, 0);

  label37 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label37);
  gtk_box_pack_start (GTK_BOX (hbox12), label37, FALSE, FALSE, 0);

  GDcontroleSaisiModifier = gtk_label_new ("");
  gtk_widget_show (GDcontroleSaisiModifier);
  gtk_fixed_put (GTK_FIXED (fixed4), GDcontroleSaisiModifier, 320, 664);
  gtk_widget_set_size_request (GDcontroleSaisiModifier, 300, 25);

  GDetabComboModifier1 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (GDetabComboModifier1);
  gtk_fixed_put (GTK_FIXED (fixed4), GDetabComboModifier1, 344, 240);
  gtk_widget_set_size_request (GDetabComboModifier1, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (GDetabComboModifier1), _("etabSang"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (GDetabComboModifier1), _("etab2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (GDetabComboModifier1), _("etab3"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (GDetabComboModifier1), _("etab4"));

  GDtypeSangComboModifier1 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (GDtypeSangComboModifier1);
  gtk_fixed_put (GTK_FIXED (fixed4), GDtypeSangComboModifier1, 296, 432);
  gtk_widget_set_size_request (GDtypeSangComboModifier1, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (GDtypeSangComboModifier1), _("A+"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (GDtypeSangComboModifier1), _("A-"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (GDtypeSangComboModifier1), _("B+"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (GDtypeSangComboModifier1), _("B-"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (GDtypeSangComboModifier1), _("O+"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (GDtypeSangComboModifier1), _("O-"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (GDtypeSangComboModifier1), _("AB+"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (GDtypeSangComboModifier1), _("AB-"));

  g_signal_connect ((gpointer) GDannulerModifierButton, "clicked",
                    G_CALLBACK (on_GDannulerModifierButton_clicked),
                    NULL);
  g_signal_connect ((gpointer) GDouiUrgenceModifier, "toggled",
                    G_CALLBACK (on_GDouiUrgenceModifier_toggled),
                    NULL);
  g_signal_connect ((gpointer) GDnonUrgenceModifier, "toggled",
                    G_CALLBACK (on_GDnonUrgenceModifier_toggled),
                    NULL);
  g_signal_connect ((gpointer) GDTraiteStatusModifier, "toggled",
                    G_CALLBACK (on_GDTraiteStatusModifier_toggled),
                    NULL);
  g_signal_connect ((gpointer) GDCoursStatusModifier, "toggled",
                    G_CALLBACK (on_GDCoursStatusModifier_toggled),
                    NULL);
  g_signal_connect ((gpointer) GDModifierButton, "clicked",
                    G_CALLBACK (on_GDModifierButton_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (GDmodife, GDmodife, "GDmodife");
  GLADE_HOOKUP_OBJECT (GDmodife, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (GDmodife, GDidEntryModifier, "GDidEntryModifier");
  GLADE_HOOKUP_OBJECT (GDmodife, label29, "label29");
  GLADE_HOOKUP_OBJECT (GDmodife, label30, "label30");
  GLADE_HOOKUP_OBJECT (GDmodife, label31, "label31");
  GLADE_HOOKUP_OBJECT (GDmodife, GDjjSpinModifier, "GDjjSpinModifier");
  GLADE_HOOKUP_OBJECT (GDmodife, GDmmSpinModifier, "GDmmSpinModifier");
  GLADE_HOOKUP_OBJECT (GDmodife, label32, "label32");
  GLADE_HOOKUP_OBJECT (GDmodife, label33, "label33");
  GLADE_HOOKUP_OBJECT (GDmodife, GDyySpinModifier, "GDyySpinModifier");
  GLADE_HOOKUP_OBJECT (GDmodife, label34, "label34");
  GLADE_HOOKUP_OBJECT (GDmodife, label40, "label40");
  GLADE_HOOKUP_OBJECT (GDmodife, GDquantiteSpinModifier, "GDquantiteSpinModifier");
  GLADE_HOOKUP_OBJECT (GDmodife, label42, "label42");
  GLADE_HOOKUP_OBJECT (GDmodife, label41, "label41");
  GLADE_HOOKUP_OBJECT (GDmodife, label39, "label39");
  GLADE_HOOKUP_OBJECT (GDmodife, label35, "label35");
  GLADE_HOOKUP_OBJECT (GDmodife, GDannulerModifierButton, "GDannulerModifierButton");
  GLADE_HOOKUP_OBJECT (GDmodife, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (GDmodife, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (GDmodife, image12, "image12");
  GLADE_HOOKUP_OBJECT (GDmodife, label36, "label36");
  GLADE_HOOKUP_OBJECT (GDmodife, GDouiUrgenceModifier, "GDouiUrgenceModifier");
  GLADE_HOOKUP_OBJECT (GDmodife, GDnonUrgenceModifier, "GDnonUrgenceModifier");
  GLADE_HOOKUP_OBJECT (GDmodife, GDTraiteStatusModifier, "GDTraiteStatusModifier");
  GLADE_HOOKUP_OBJECT (GDmodife, GDCoursStatusModifier, "GDCoursStatusModifier");
  GLADE_HOOKUP_OBJECT (GDmodife, GDModifierButton, "GDModifierButton");
  GLADE_HOOKUP_OBJECT (GDmodife, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (GDmodife, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (GDmodife, image13, "image13");
  GLADE_HOOKUP_OBJECT (GDmodife, label37, "label37");
  GLADE_HOOKUP_OBJECT (GDmodife, GDcontroleSaisiModifier, "GDcontroleSaisiModifier");
  GLADE_HOOKUP_OBJECT (GDmodife, GDetabComboModifier1, "GDetabComboModifier1");
  GLADE_HOOKUP_OBJECT (GDmodife, GDtypeSangComboModifier1, "GDtypeSangComboModifier1");

  return GDmodife;
}

GtkWidget*
create_GDstatistique (void)
{
  GtkWidget *GDstatistique;
  GtkWidget *fixed5;
  GtkWidget *label49;
  GtkWidget *GDannulerStatistiqueButton;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image15;
  GtkWidget *label48;
  GtkWidget *label44;
  GtkWidget *GDtypePlusDemandeLabelStatistique;
  GtkWidget *label43;
  GtkWidget *GDpourcentageDemandeLabelStatistique;
  GtkWidget *GDcontroleSaisiStatistique;
  GtkWidget *GDstatistiqueButton1;
  GtkWidget *alignment16;
  GtkWidget *hbox16;
  GtkWidget *image17;
  GtkWidget *label51;
  GtkWidget *label52;
  GtkWidget *GDcomboEtabStatistique;
  GtkWidget *GDstatistiqueButton;
  GtkWidget *alignment17;
  GtkWidget *hbox17;
  GtkWidget *image18;
  GtkWidget *label53;

  GDstatistique = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (GDstatistique), _("Statistique"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (GDstatistique), fixed5);
  gtk_widget_set_size_request (fixed5, 645, 393);

  label49 = gtk_label_new (_("Statistique"));
  gtk_widget_show (label49);
  gtk_fixed_put (GTK_FIXED (fixed5), label49, 272, 48);
  gtk_widget_set_size_request (label49, 109, 17);

  GDannulerStatistiqueButton = gtk_button_new ();
  gtk_widget_show (GDannulerStatistiqueButton);
  gtk_fixed_put (GTK_FIXED (fixed5), GDannulerStatistiqueButton, 120, 296);
  gtk_widget_set_size_request (GDannulerStatistiqueButton, 168, 42);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (GDannulerStatistiqueButton), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image15 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox14), image15, FALSE, FALSE, 0);

  label48 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label48);
  gtk_box_pack_start (GTK_BOX (hbox14), label48, FALSE, FALSE, 0);

  label44 = gtk_label_new (_("Type de sang la plus demand\303\251 :"));
  gtk_widget_show (label44);
  gtk_fixed_put (GTK_FIXED (fixed5), label44, 96, 240);
  gtk_widget_set_size_request (label44, 233, 17);

  GDtypePlusDemandeLabelStatistique = gtk_label_new ("");
  gtk_widget_show (GDtypePlusDemandeLabelStatistique);
  gtk_fixed_put (GTK_FIXED (fixed5), GDtypePlusDemandeLabelStatistique, 336, 240);
  gtk_widget_set_size_request (GDtypePlusDemandeLabelStatistique, 49, 17);

  label43 = gtk_label_new (_("pourcentage Domande : "));
  gtk_widget_show (label43);
  gtk_fixed_put (GTK_FIXED (fixed5), label43, 104, 144);
  gtk_widget_set_size_request (label43, 202, 17);

  GDpourcentageDemandeLabelStatistique = gtk_label_new ("");
  gtk_widget_show (GDpourcentageDemandeLabelStatistique);
  gtk_fixed_put (GTK_FIXED (fixed5), GDpourcentageDemandeLabelStatistique, 296, 144);
  gtk_widget_set_size_request (GDpourcentageDemandeLabelStatistique, 49, 17);

  GDcontroleSaisiStatistique = gtk_label_new ("");
  gtk_widget_show (GDcontroleSaisiStatistique);
  gtk_fixed_put (GTK_FIXED (fixed5), GDcontroleSaisiStatistique, 480, 104);
  gtk_widget_set_size_request (GDcontroleSaisiStatistique, 161, 17);

  GDstatistiqueButton1 = gtk_button_new ();
  gtk_widget_show (GDstatistiqueButton1);
  gtk_fixed_put (GTK_FIXED (fixed5), GDstatistiqueButton1, 272, 184);
  gtk_widget_set_size_request (GDstatistiqueButton1, 192, 43);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (GDstatistiqueButton1), alignment16);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox16);

  image17 = gtk_image_new_from_stock ("gtk-find-and-replace", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_box_pack_start (GTK_BOX (hbox16), image17, FALSE, FALSE, 0);

  label51 = gtk_label_new_with_mnemonic (_("pourcentage demande "));
  gtk_widget_show (label51);
  gtk_box_pack_start (GTK_BOX (hbox16), label51, FALSE, FALSE, 0);

  label52 = gtk_label_new (_("Etabalissement :"));
  gtk_widget_show (label52);
  gtk_fixed_put (GTK_FIXED (fixed5), label52, 112, 112);
  gtk_widget_set_size_request (label52, 136, 17);

  GDcomboEtabStatistique = gtk_combo_box_entry_new_text ();
  gtk_widget_show (GDcomboEtabStatistique);
  gtk_fixed_put (GTK_FIXED (fixed5), GDcomboEtabStatistique, 256, 104);
  gtk_widget_set_size_request (GDcomboEtabStatistique, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (GDcomboEtabStatistique), _("etabSang"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (GDcomboEtabStatistique), _("etab2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (GDcomboEtabStatistique), _("etab3"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (GDcomboEtabStatistique), _("etab4"));

  GDstatistiqueButton = gtk_button_new ();
  gtk_widget_show (GDstatistiqueButton);
  gtk_fixed_put (GTK_FIXED (fixed5), GDstatistiqueButton, 376, 296);
  gtk_widget_set_size_request (GDstatistiqueButton, 240, 44);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (GDstatistiqueButton), alignment17);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox17);

  image18 = gtk_image_new_from_stock ("gtk-leave-fullscreen", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image18);
  gtk_box_pack_start (GTK_BOX (hbox17), image18, FALSE, FALSE, 0);

  label53 = gtk_label_new_with_mnemonic (_("type du sang la plus demande"));
  gtk_widget_show (label53);
  gtk_box_pack_start (GTK_BOX (hbox17), label53, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) GDannulerStatistiqueButton, "clicked",
                    G_CALLBACK (on_GDannulerStatistiqueButton_clicked),
                    NULL);
  g_signal_connect ((gpointer) GDstatistiqueButton1, "clicked",
                    G_CALLBACK (on_GDstatistiqueButton1_clicked),
                    NULL);
  g_signal_connect ((gpointer) GDstatistiqueButton, "clicked",
                    G_CALLBACK (on_GDstatistiqueButton_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (GDstatistique, GDstatistique, "GDstatistique");
  GLADE_HOOKUP_OBJECT (GDstatistique, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (GDstatistique, label49, "label49");
  GLADE_HOOKUP_OBJECT (GDstatistique, GDannulerStatistiqueButton, "GDannulerStatistiqueButton");
  GLADE_HOOKUP_OBJECT (GDstatistique, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (GDstatistique, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (GDstatistique, image15, "image15");
  GLADE_HOOKUP_OBJECT (GDstatistique, label48, "label48");
  GLADE_HOOKUP_OBJECT (GDstatistique, label44, "label44");
  GLADE_HOOKUP_OBJECT (GDstatistique, GDtypePlusDemandeLabelStatistique, "GDtypePlusDemandeLabelStatistique");
  GLADE_HOOKUP_OBJECT (GDstatistique, label43, "label43");
  GLADE_HOOKUP_OBJECT (GDstatistique, GDpourcentageDemandeLabelStatistique, "GDpourcentageDemandeLabelStatistique");
  GLADE_HOOKUP_OBJECT (GDstatistique, GDcontroleSaisiStatistique, "GDcontroleSaisiStatistique");
  GLADE_HOOKUP_OBJECT (GDstatistique, GDstatistiqueButton1, "GDstatistiqueButton1");
  GLADE_HOOKUP_OBJECT (GDstatistique, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (GDstatistique, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (GDstatistique, image17, "image17");
  GLADE_HOOKUP_OBJECT (GDstatistique, label51, "label51");
  GLADE_HOOKUP_OBJECT (GDstatistique, label52, "label52");
  GLADE_HOOKUP_OBJECT (GDstatistique, GDcomboEtabStatistique, "GDcomboEtabStatistique");
  GLADE_HOOKUP_OBJECT (GDstatistique, GDstatistiqueButton, "GDstatistiqueButton");
  GLADE_HOOKUP_OBJECT (GDstatistique, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (GDstatistique, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (GDstatistique, image18, "image18");
  GLADE_HOOKUP_OBJECT (GDstatistique, label53, "label53");

  return GDstatistique;
}

