/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *GDaffiche;
  GtkWidget *GDsupprime;
  GtkWidget *GDajoute;
  GtkWidget *GDmodife;
  GtkWidget *GDstatistique;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  GDaffiche = create_GDaffiche ();
  gtk_widget_show (GDaffiche);
 // GDsupprime = create_GDsupprime ();
 // gtk_widget_show (GDsupprime);
 // GDajoute = create_GDajoute ();
//  gtk_widget_show (GDajoute);
 // GDmodife = create_GDmodife ();
 // gtk_widget_show (GDmodife);
  // GDstatistique = create_GDstatistique ();
 // gtk_widget_show (GDstatistique);

  gtk_main ();
  return 0;
}

